name: Deploy Laravel App via FTP

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, dom, filter, gd, json

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    # Removed composer install and npm install/build


    - name: Set permissions
      run: chmod -R 755 storage bootstrap/cache

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21
        local-dir: ./        # Adjust if you only want to deploy `public/` or a `build/` directory
        server-dir: /
        exclude: |
          .git*
          .github/
          node_modules/
          *.env
          *.env.example
          *.md
          *.txt
          tests/
          storage/framework/sessions/*
          storage/framework/views/*
          storage/logs/*
